server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zoni_place?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: zoni1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: zoni-super-secret-key-must-be-at-least-32-characters-long!
  access-token-expire: 1800000

kakao:
  rest-api-key: a373f72381f46f4957cfb989cac9cbc3 # 카카오디벨로퍼 ZONI test rest api key 값, 카카오맵도 ZONI test로 활성화 함

cache:
  search-ttl: 3600
  popular-ttl: 1800